// Methodology panel content: one entry per design decision. Every number comes from the white paper
// (docs/whitepaper), which cites the repo file behind it. trade.win = index of the adopted row (-1: none).
// figs: [file in assets/method/, caption]. sec: white-paper section title.
export const METHOD = [
  {
    step: "Configuration",
    decision: "A blended wing body with tip fins and a folding centre pusher.",
    why: "The phone must sit over the battery at the centre of gravity, and the aircraft lands on its belly. A blended centre body is 57 mm deep at the battery station, inside the lifting surface, and its flat 520 mm belly carries a replaceable skid. The pusher keeps the prop out of the cameras' view and folds flat for landing. The price is the narrow CG window of a tailless aircraft, 12.5 mm, which a per-phone battery notch meets.",
    trade: { cols: ["Layout", "Phone + battery at CG", "Belly landing", "CG window"], win: 2, rows: [
      ["Conventional tail", "needs a fuselage pod", "boom and tail exposed", "wide"],
      ["Plain flying wing", "32 mm deep root: pod needed", "flat, no protected bay", "narrow"],
      ["Blended wing + tip fins", "57 mm deep, inside the wing", "flat belly on a TPU sled", "narrow (12.5 mm)"]] },
    method: "Trade on repository numbers; constraint diagram of power loading against wing loading; range tracked across design revisions.",
    stats: [["57", "mm", "centre-body depth at the battery"], ["12.5", "mm", "CG window (6–10 % margin)"], ["51.6", "g/dm²", "wing loading at 2.68 kg"]],
    figs: [["aero_sizing.webp", "Planform with neutral point and CG; constraint diagram; range by design revision."]],
    sec: "Configuration and sizing",
  },
  {
    step: "Airfoils + CFD",
    decision: "Reflexed MH45 wing and MH60 centre body, with the stall speed set by CFD rather than the fast model.",
    why: "At 9–22 m/s the wing runs at Reynolds numbers of 1.1–7.8 × 10⁵, where laminar separation bubbles decide stall. The fast model (NeuralFoil, trained on XFOIL) gave the wingtip section a maximum lift coefficient of 1.19. SU2 RANS with transition modelling showed the leading-edge bubble bursting at 9–11°, capping it at 0.87–0.92, about 25 % lower. We cut the aircraft's maximum lift coefficient from 1.01 to 0.90, which raised the stall estimate to about 9.6 m/s untrimmed at the 2.68 kg CAD mass (9.8 m/s trimmed) and set the autopilot's stall, minimum and approach airspeeds.",
    trade: { cols: ["Model (MH45, Re 122k)", "c_l,max", "c_d at c_l 0.35", "What it captures"], win: 1, rows: [
      ["NeuralFoil (fast)", "1.19", "0.0129", "XFOIL-trained; optimistic near stall"],
      ["SU2 SST + Langtry–Menter", "0.87–0.92", "0.0169", "the laminar bubble and its burst"],
      ["SU2 SST, fully turbulent", "1.18", "0.0161", "no bubble; over-predicts drag"]] },
    method: "SU2 8.5 incompressible RANS on a 98k-cell gmsh mesh (first cell 1.5 × 10⁻⁵ c); the 189k-cell fine mesh agreed in lift within 0.6 %. Three sections swept from −2° to 16°, about 43 CPU-hours.",
    stats: [["0.87–0.92", "", "tip c_l,max (SU2 transition)"], ["−25", "%", "vs the fast model"], ["9.8", "m/s", "trimmed stall, 2.68 kg"]],
    figs: [["cfd_mh45_stall.webp", "Near stall the bubble moves to the leading edge and bursts. Lift peaks at c_l 0.92 at 10°, about 25 % below the XFOIL-based estimate (SU2, SST + Langtry–Menter)."],
           ["cfd_mh45_cruise.webp", "Cruise, 4.5°: a laminar separation bubble sits over mid-chord, with flow reversed from 22 % to 82 % of chord (near-wall zoom, height stretched ×11)."],
           ["cfd_mh45_cpcf.webp", "Skin friction goes negative inside the bubble in the transition model (solid); fully turbulent RANS (dashed) never separates and misses it."],
           ["cfd_mesh.webp", "The 63k-node hybrid mesh: 45 quad layers resolve the boundary layer down to 1.5 × 10⁻⁵ chord."],
           ["aero_cfd_mh45.webp", "Lift, drag and pitching moment: NeuralFoil against both SU2 models."]],
    sec: "Aerodynamics",
  },
  {
    step: "Performance",
    decision: "Cruise at 14 m/s on a 4S2P Li-ion pack with an 11×7 folding prop.",
    why: "At the 2.68 kg CAD mass, trimmed L/D is 11.7 at 14 m/s and peaks at 12.1 at 12–12.5 m/s; cruising a little faster buys wind penetration and photo cadence for a few percent of range. The Molicel P45B pack stores 129.6 Wh; a LiPo would need more than 216 Wh/kg at pack level to match it. The 11×7, chosen from measured UIUC propeller data, is within 1.4 % of the most efficient prop that clears the dolly and gives the most launch thrust. At a 2,000 m, 35 °C site the aircraft still works, with a longer landing run.",
    trade: { cols: ["Site (2.52 kg basis)", "Density altitude", "Stall (true)", "Landing run", "Endurance"], win: -1, rows: [
      ["Sea level, 15 °C", "0 km", "9.3 m/s", "60 m", "baseline"],
      ["2,000 m, 35 °C", "3.1 km", "10.8 m/s", "80 m", "−12 %"]] },
    method: "AeroSandbox AeroBuildup (NeuralFoil sections) with a 0.014 drag build-up, trimmed at every speed; VSPAERO cross-check; BEMT against UIUC data; ISA density-altitude scaling.",
    stats: [["11.7", "", "trimmed L/D at 14 m/s"], ["≈58", "km", "range, 20 % reserve kept"], ["1.16–1.33", "h", "endurance"]],
    figs: [["aero_polar_ld.webp", "Trimmed drag polars and L/D against airspeed at 2.43 and 2.52 kg, with the VSPAERO sweep."],
           ["aero_hothigh.webp", "Stall and cruise speed, endurance, landing run and launch thrust against density altitude."],
           ["aero_prop.webp", "11×7 folding prop: BEMT against UIUC data, and efficiency against speed."]],
    sec: "Propulsion and performance",
  },
  {
    step: "Stability",
    decision: "An 8 % static margin, trim from reflex and washout, and taller fins canted outboard.",
    why: "A tailless wing has to trim itself. Reflexed sections plus 3° of washout give a nose-up zero-lift moment (+0.014), so cruise needs only −2.8° of elevon; a conventional cambered section would need −10.5° and lose a full point of L/D. The first 160 mm fins left the Dutch roll lightly damped. Raising them to 200 mm fixed it but slowed the spiral; canting them 10° outboard recovered the spiral.",
    trade: { cols: ["Fins", "Dutch-roll damping ζ", "Spiral time to double"], win: 1, rows: [
      ["160 mm, vertical", "0.088", "30 s"],
      ["200 mm, 10° cant (adopted)", "0.103", "39 s"]] },
    method: "Vortex-lattice stability derivatives, linearised six-degree-of-freedom modes, and root-locus sweeps of static margin and fin height against MIL-F-8785C handling levels.",
    stats: [["8.0", "%", "static margin"], ["+0.014", "", "zero-lift pitching moment"], ["0.103", "", "Dutch-roll damping"]],
    figs: [["stab_modes.webp", "Root loci: short period and phugoid against static margin; Dutch roll and spiral against fin height and cant."],
           ["stab_trim.webp", "Pitching moment against lift for the design, no washout and a conventional section; trim elevon against speed."]],
    sec: "Stability, control and flight dynamics",
  },
  {
    step: "Crow airbrake",
    decision: "Split elevons that open as a clamshell airbrake: upper halves 31° up, lower halves 19° down, a setting chosen by CFD.",
    why: "Landing sites can be as short as 60 m, so the approach must be steep with no flaps and no tail. Each elevon is split into halves on one hinge that ArduPilot drives as differential spoilers. The first setting, 51° up and 12° down, failed a CFD trim study: its nose-up moment used most of the pitch-trim range, and once the autopilot trimmed it the lower halves hung inside the skid's crush margin. The CFD also showed that after trim the halves always end up where the total opening puts them, so the fix was a new split, not new hardware.",
    trade: { cols: ["Crow (up / down)", "Trim needed", "Authority left", "Glide", "Clearance"], win: 3, rows: [
      ["51° / 12° (first)", "+15.2° / +11.3°", "9.8°", "3.8:1", "8.9 mm"],
      ["±30°", "−4.3° / −8.0°", "17.0°", "4.1:1", "10.3 mm"],
      ["33° / 17°", "+3.8° / +0.5°", "21.2°", "5.2–5.3:1", "14.7 mm"],
      ["31° / 19° (adopted)", "+1.8° / −1.5°", "23.2°", "5.3–5.4:1", "15–18 mm"]] },
    method: "SU2 RANS of the split section with its cavity meshed (118k cells), drag calibrated on a 60° split flap; section data fitted and fed into the vortex-lattice model; trim solved at 12.5 m/s at both CG limits (pairs are static margin 6 % / 9 %); lower-half clearance checked against the skid over 0–4° touchdown pitch. The planner's final moved to 6.0:1 to keep a 10 % glide margin.",
    stats: [["23.2", "°", "pitch authority left after trim"], ["5.4:1", "", "approach glide (planner flies 6:1)"], ["≥15", "mm", "lower-half ground clearance"]],
    figs: [["crow_flowfield.webp", "Flow through the open split elevon (SU2): clean, the first 51°/12° setting, and the adopted setting after trim."],
           ["crow_trim.webp", "Trim elevon and remaining pitch authority against crow setting."],
           ["crow_glide.webp", "Approach glide ratio against crow setting, with the planner's 6.0:1 final."]],
    sec: "Stability, control and flight dynamics",
  },

  {
    step: "Launch + landing",
    decision: "A passive dolly for takeoff and a flared belly landing on a deep skid sled.",
    why: "The running pusher prop reaches 134 mm below the thrust line, so the aircraft cannot take off from its belly. It rides a dolly at its 8° lift-off attitude and simply flies off at about 11.4 m/s, with no latch on the aircraft; feelers then fold the towers away. Torsion-bar suspension at 3.5 Hz keeps the roll clean over 5–20 mm bumps. For landing, the autopilot flares on a rangefinder.",
    trade: { cols: ["Launch", "Needs", "Status"], win: 2, rows: [
      ["Belly takeoff", "—", "prop strikes the ground"],
      ["Hand or bungee", "a thrower or a bungee", "supported; not simulated"],
      ["Passive dolly (adopted)", "≤ 3 m/s crosswind, bumps ≤ 15 mm", "27/27 cases and 66/66 bump runs pass"]] },
    method: "3-D dolly dynamics with tyre and suspension models; flare simulation with the autopilot's height error swept; SITL touchdowns.",
    stats: [["15.1", "m", "dolly roll to lift-off"], ["0.97", "m/s", "nominal touchdown sink"], ["43/60", "m", "worst landing run (soft turf)"]],
    figs: [["stab_dolly.webp", "Dolly takeoff: speeds, attitude, ball loads, lift and thrust through release."],
           ["stab_flare.webp", "Flare at 2.68 kg and 13 m/s on the 6.0:1 final with the new crow: trajectories, and touchdown sink against the autopilot's height error."]],
    sec: "Launch and recovery",
  },
  {
    step: "Structures",
    decision: "Size the structure for the belly landing, not for flight.",
    why: "The worst flight case, a rolling pull-up, puts 31.2 N·m on the wing root; the landing puts 84.5 N·m. The first skid gave 117 g at the CG in a 3 m/s abuse landing. A deeper TPU sled with nothing rigid near its wear face brought the design load to 50 g. The landing then forced a thicker joiner and a machined spar node, redesigned through three rounds of FEA.",
    trade: { cols: ["Part", "First design", "Final"], win: -1, rows: [
      ["Skid", "as built: 117 g at CG", "deep sled: 50 g"],
      ["Joiner tube", "12×10: RF 0.67", "12×8: RF 1.03"],
      ["Spar node", "PETG-CF box: SF 0.41", "7075 node v3: SF 1.50"],
      ["Node to keel", "tab + inserts: SF 0.53", "web + M3 8.8 through-bolts"]] },
    method: "V–n diagram with a 7.6 m/s UAS gust; vortex-lattice spanloads; beam models; gmsh + CalculiX FEA checked against hand solutions to within 1.04 %; landing-impact model by body station.",
    stats: [["84.5", "N·m", "landing root bending"], ["31.2", "N·m", "worst flight case"], ["50", "g", "design landing load at CG"]],
    figs: [["struct_landing_g.webp", "Ultimate landing load by body station for the as-built skid, a thin-wall skid and the deep sled."],
           ["struct_node_fea.webp", "CalculiX FEA of the 7075 spar node v3 under the landing transient."],
           ["struct_vn.webp", "V–n diagram: the +5.6 / −3.5 design envelope."]],
    sec: "Structures and materials",
  },
  {
    step: "Foam wing",
    decision: "EPP foam outer wings covered in two layers of iron-on film.",
    why: "The printed wing with its internal lattice came to 438 g per side and overloaded the joiner. Foam with glass fibre is lighter and stiffer but needs epoxy layup, which this build rules out. EPP with two layers of Oracover is 353–357 g per side, survives crashes, takes a normal covering iron and clears the flutter requirement. One layer would not, so every build passes a coupon test first.",
    trade: { cols: ["Outer wing", "Mass / side", "Flutter", "Verdict"], win: 2, rows: [
      ["Printed + lattice", "438 g", "67 m/s", "joiner overloaded (RF 0.90)"],
      ["Foam + glass / epoxy", "281–309 g", "68–70 m/s", "needs composite layup"],
      ["EPP + 2× Oracover (adopted)", "353–357 g", "44.6 m/s (need 41.9)", "buildable, crash-tolerant"]] },
    method: "Strip-theory flutter with film shear stiffness, torsion and reversal checks; acceptance by a 300 mm bar twist test.",
    stats: [["357", "g", "per side"], ["44.6", "m/s", "flutter speed (need 41.9)"], ["≥54", "N/mm", "film G·t acceptance"]],
    figs: [["struct_wing_options.webp", "Outer-wing options: mass per side against flutter speed."],
           ["struct_film_gt.webp", "Film build-ups on the EPP wing: nominal and 20 % soft against the requirement."]],
    sec: "Structures and materials",
  },
  {
    step: "Onboard system",
    decision: "An ordinary Android phone is the companion computer; the autopilot owns every failsafe.",
    why: "The phone runs on its own battery for 3.4 h (2.4 h worst case) against 1.24 h of flight, so it costs the flight pack nothing; a 4.3 W single-board computer would cost 6 % of endurance. It brings a neural processor, storage and a screen, and the operator already owns one. The costs are heat, handled by a NACA duct that drops the phone from 57 to 47 °C in cruise on a 35 °C day, and fit: 28 phone profiles, each with a printed insert.",
    trade: { cols: ["Computer", "Energy", "Cost", "Heat"], win: 0, rows: [
      ["Android phone (adopted)", "own battery, 3.4 h", "already owned", "full payload below ≈38 °C"],
      ["Single-board computer", "from the pack: −6 % endurance", "board, storage, cooling, modem", "sized freely"]] },
    method: "Rail-by-rail power budget; thermal network of the phone bay and duct; landing shock and vibration model of the phone mount; camera ground-sample and blur geometry.",
    stats: [["3.4", "h", "phone battery, typical"], ["57→47", "°C", "phone with the NACA duct"], ["3.9", "cm/px", "RGB at 100 m"]],
    figs: [["sys_architecture.webp", "Avionics: data, power and radio links; LTE is used on the ground only."],
           ["sys_camera.webp", "Ground sample distance against height, and the along-track error budget at 14 m/s."]],
    sec: "Avionics, onboard computing and payload",
  },
  {
    step: "Ground planner",
    decision: "Landing sites are chosen before takeoff and written into the autopilot's mission.",
    why: "From free data (30 m terrain, ESA land cover, OpenStreetMap) the planner finds open, flat patches with at least 60 m of run away from buildings, roads and power lines, and checks that every point on the route can reach one with the reserve. Each site becomes an ArduPilot landing sequence, so the autopilot's own failsafes can reach the nearest vetted site without the phone; this is tested in simulation, not yet in flight. The required run grows with density altitude.",
    trade: { cols: ["Approach", "Who picks the site", "Needs the phone?"], win: 2, rows: [
      ["Return to launch", "fixed", "no, but may be out of reach"],
      ["Choose in flight", "phone, by camera", "yes"],
      ["Plan before takeoff (adopted)", "planner; autopilot flies it", "no; the phone only refines"]] },
    method: "Terrain slope and roughness along 12 headings, land-cover filter, OSM buffers, reachability with glide ratio and energy reserve, and σ-scaling of the landing run.",
    stats: [["91", "ha", "New Jersey example"], ["8", "", "vetted sites plus home"], ["60→80", "m", "run: sea level → 2,000 m, 35 °C"]],
    figs: [["sys_njplan.webp", "Planner output for a 91 ha New Jersey survey: lines, vetted landing sites and approaches."],
           ["sys_da_run.webp", "Required landing run against site elevation and temperature."]],
    sec: "Ground planning software",
  },
  {
    step: "Verification",
    decision: "Prove the safety logic in simulation now; prove the physics on the first airframe.",
    why: "The landing-site and phone-loss failsafes run end to end in ArduPilot software-in-the-loop with the aircraft's own parameters and a simulated flare lidar: a return-to-launch goes to the nearest site, the phone can divert, a go-around on final lands at the other site, losing the phone never interrupts the flight, and the autopilot refuses to arm without a ground-station link. Automated audits of the CAD solids check whether each part prints and each unit can be serviced, and list the fixes. The first build follows a staged test plan, and the stall is checked in flight before anything below 10 m/s is trusted.",
    trade: { cols: ["SITL test", "Result"], win: -1, rows: [
      ["Failsafe goes to the nearest site", "landed 25 m from the aim point; crow opened"],
      ["Phone diverts on approach", "landed 27 m from the other site"],
      ["Go-around on final, then divert", "climbed out, landed 29 m from the other site"],
      ["Phone lost, ground link up", "kept flying the survey; no failsafe needed"],
      ["Phone and ground link lost", "failsafe after 19 s; landed 27 m from the nearest site"],
      ["No ground link at arming", "arming refused by the autopilot"],
      ["Mission change in plain RTL", "firmware quirk documented and handled"]] },
    method: "ArduPlane 4.7.1 SITL driven by pytest over MAVLink, with the phone and ground station on their own links; unit tests for the planner and the phone app; DFM and service audits on the exported CAD.",
    stats: [["9/9", "", "SITL tests"], ["57", "", "ground-software tests"], ["142", "", "phone-app tests"]],
    figs: [],
    sec: "Verification status and test plan",
  },
];
