// Images and film for the placeholder slots (data-slot in index.html; q-* are the Design-quality tabs).
// Only finished, reviewed media are listed; a slot without an entry keeps its placeholder.
// tag: what the viewer is looking at. Renders are illustrations; nothing here has flown.
export const SHOTS = {
  "use-conservation": { src: "assets/renders/use_conservation", tag: "Render",
    alt: "BLUEBIRD at dawn over the Laikipia plateau in Kenya, its thermal camera footprint on elephants and zebra at a waterhole, with Mt Kenya on the horizon.",
    cap: "Render. First light over the Laikipia plateau: BLUEBIRD at 100 m, its thermal camera's footprint on elephants and zebra at a waterhole, with the live thermal view inset. Terrain Copernicus GLO-30; imagery Sentinel-2 (2025)." },
  "use-agriculture": { src: "assets/renders/use_agriculture", tag: "Render",
    alt: "BLUEBIRD surveying New Jersey farmland: glowing survey lines and photo footprints over fields and tree lines.",
    cap: "Render. Survey line 10 of 20 over Franklin Township farmland at 100 m: each photo covers 149 × 118 m at 3.9 cm/px, lines 44.6 m apart. Plan from the BLUEBIRD ground planner; imagery USDA NAIP 2022." },
  "status-wide": { src: "assets/renders/use_conservation_laptop", tag: "Render",
    alt: "A laptop ground station on a table at the edge of the savanna at dawn, showing a thermal detection waiting for the operator.",
    cap: "Render. The ground station at dawn: a thermal detection waits for the operator. Nothing happens on the aircraft until a person decides." },
  "card-aircraft": { src: "assets/renders/card_aircraft", tag: "Render",
    alt: "BLUEBIRD, a 1.8 m blended-wing drone in its white and sky-blue livery, on a light studio background.",
    cap: "BLUEBIRD: a 1.8 m blended wing in its Rev C livery. Render from the design CAD; the aircraft has not been built yet." },
  "card-phonebay": { src: "assets/renders/card_phonebay", tag: "Render",
    alt: "The centre body with its hatch flipped forward: the phone on the hatch underside, screen up, and the battery pack in the tray below.",
    cap: "One motion: the hatch flips forward, the phone comes up screen first, and the battery is right below. Render from the CAD." },
  "card-dolly": { src: "assets/renders/card_dolly", tag: "Render",
    alt: "BLUEBIRD seated on its wheeled launch dolly at an 8 degree lift-off attitude.",
    cap: "Seated on the passive launch dolly at its 8° lift-off attitude. Render from the CAD." },
  "q-phone": { src: "assets/renders/q_phone_brain", tag: "Render",
    alt: "X-ray view of the aircraft with the phone, flight controller, cameras and servos lifted out and glowing data-flow lines between them.",
    cap: "The phone runs the mission over MAVLink; the flight controller alone drives the servos and motor, so a phone failure is never a flight-safety event. Render." },
  "q-repair": { src: "assets/renders/q_exploded", tag: "Render",
    alt: "Exploded view: printed centre body, foam outer wings on a carbon spar, V-node, skid sled, motor and folding prop.",
    cap: "Printed centre body, EPP foam wings on a carbon spar, a TPU wear sled: every part replaceable in the field. Render.",
    more: [
      { src: "assets/renders/q_breakdown", tag: "Render", alt: "The aircraft in three pieces with the hex key and two bolts.",
        cap: "Three pieces for transport: each wing slides off its carbon joiner after one bolt and one plug. Render." },
      { src: "assets/renders/q_breakdown_case", tag: "Render", alt: "The three pieces packed in a foam-lined case.",
        cap: "All three pieces in one case (illustrative). Render." },
    ] },
  "card-planner": { src: "assets/renders/card_planner", tag: "Planner output",
    alt: "Ground planner map of a 91 ha survey near Franklin Township, New Jersey: survey lines, eight vetted landing sites with 6.0:1 finals, and the predicted site.",
    cap: "Ground planner output for a 91 ha survey near Franklin Township, NJ. Every landing site passed slope, land-cover, obstacle and power-line checks and gets a 240 m, 6.0:1 final. Open data: Copernicus DEM, ESA WorldCover, © OpenStreetMap contributors." },
  "q-landing": { src: "assets/renders/q_landing_sitl", tag: "Simulation",
    alt: "Map of an ArduPlane software-in-the-loop flight: after the ground link is cut, the failsafe flies to the nearest vetted landing site and lands.",
    cap: "ArduPlane 4.7.1 software-in-the-loop flying the planner's mission. With the link cut mid-survey, the failsafe picked the nearest vetted site (L2, 203 m), not the first in the mission (L1, 769 m), and landed after a 9.5° final. Simulation only; nothing has flown." },
  "q-tools": { src: "assets/renders/q_tools", tag: "Project outputs",
    alt: "Collage of project outputs: FreeCAD model, SU2 flow field, CalculiX stress plot, AeroSandbox span load, ArduPilot simulation map and the LaTeX white paper.",
    cap: "Every image on this page was made with free software: FreeCAD, SU2, CalculiX, AeroSandbox, ArduPilot and LaTeX." },
};
export const FILM = { src: "assets/renders/bluebird_film.mp4", poster: "assets/renders/bluebird_film_end.jpg" };
